#!/bin/bash
set -e

NETWORK="${1:-testnet}"
OWNER="${2}"

if [ -z "$OWNER" ]; then
  echo "Usage: ./scripts/deploy.sh <network> <owner_address>"
  echo "  network: testnet | mainnet"
  echo "  owner_address: terra1... address that will own the factory and router"
  exit 1
fi

case "$NETWORK" in
  testnet)
    CHAIN_ID="rebel-2"
    NODE="https://terra-classic-rpc.publicnode.com:443"
    ;;
  mainnet)
    CHAIN_ID="columbus-5"
    NODE="https://terra-classic-rpc.publicnode.com:443"
    ;;
  *)
    echo "Unknown network: $NETWORK (use testnet or mainnet)"
    exit 1
    ;;
esac

ARTIFACTS_DIR="$(dirname "$0")/../artifacts"

echo "=============================================="
echo "CL8Y DEX Deployment - $NETWORK ($CHAIN_ID)"
echo "=============================================="
echo ""
echo "Owner: $OWNER"
echo "Node:  $NODE"
echo ""

if [ ! -d "$ARTIFACTS_DIR" ]; then
  echo "ERROR: artifacts/ directory not found."
  echo "Run 'make build-optimized' first to generate optimized wasm files."
  exit 1
fi

echo "Step 1: Upload contracts"
echo "========================"
echo ""
echo "Upload CW20 Base (LP token):"
echo "  terrad tx wasm store $ARTIFACTS_DIR/cw20_base.wasm \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 5000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""
echo "Upload Factory:"
echo "  terrad tx wasm store $ARTIFACTS_DIR/cl8y_dex_factory.wasm \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 5000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""
echo "Upload Pair:"
echo "  terrad tx wasm store $ARTIFACTS_DIR/cl8y_dex_pair.wasm \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 5000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""
echo "Upload Router:"
echo "  terrad tx wasm store $ARTIFACTS_DIR/cl8y_dex_router.wasm \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 5000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""
echo "Upload Fee Discount:"
echo "  terrad tx wasm store $ARTIFACTS_DIR/cl8y_dex_fee_discount.wasm \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 5000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""

echo "Step 2: Query code IDs"
echo "======================"
echo ""
echo "After each upload, query the tx to get the code_id:"
echo "  terrad query tx <TX_HASH> --node $NODE --output json | jq '.logs[0].events[] | select(.type==\"store_code\") | .attributes[] | select(.key==\"code_id\") | .value'"
echo ""

echo "Step 3: Instantiate Factory"
echo "==========================="
echo ""
echo "Replace <CW20_CODE_ID>, <PAIR_CODE_ID> with actual code IDs:"
echo ""
echo "  terrad tx wasm instantiate <FACTORY_CODE_ID> '{\"governance\": \"$OWNER\", \"treasury\": \"$OWNER\", \"default_fee_bps\": 180, \"pair_code_id\": <PAIR_CODE_ID>, \"lp_token_code_id\": <CW20_CODE_ID>, \"whitelisted_code_ids\": [<CW20_CODE_ID>]}' \\"
echo "    --label \"cl8y-dex-factory\" \\"
echo "    --admin $OWNER \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 2000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""

echo "Step 4: Instantiate Router"
echo "=========================="
echo ""
echo "Replace <FACTORY_ADDRESS> with the factory contract address:"
echo ""
echo "  terrad tx wasm instantiate <ROUTER_CODE_ID> '{\"factory\": \"<FACTORY_ADDRESS>\"}' \\"
echo "    --label \"cl8y-dex-router\" \\"
echo "    --admin $OWNER \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 2000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""

echo "Step 5: Instantiate Fee Discount"
echo "================================"
echo ""
echo "Replace <FEE_DISCOUNT_CODE_ID> with the actual code ID."
echo "CL8Y mainnet address: terra16wtml2q66g82fdkx66tap0qjkahqwp4lwq3ngtygacg5q0kzycgqvhpax3"
echo ""
echo "  terrad tx wasm instantiate <FEE_DISCOUNT_CODE_ID> '{\"governance\": \"$OWNER\", \"cl8y_token\": \"terra16wtml2q66g82fdkx66tap0qjkahqwp4lwq3ngtygacg5q0kzycgqvhpax3\"}' \\"
echo "    --label \"cl8y-dex-fee-discount\" \\"
echo "    --admin $OWNER \\"
echo "    --from wallet \\"
echo "    --chain-id $CHAIN_ID \\"
echo "    --node $NODE \\"
echo "    --gas auto --gas-adjustment 1.3 \\"
echo "    --fees 2000000uluna \\"
echo "    --broadcast-mode sync -y"
echo ""

echo "Step 6: Configure Fee Discount Tiers"
echo "====================================="
echo ""
echo "Replace <FEE_DISCOUNT_ADDRESS> with the fee discount contract address:"
echo ""
echo "Add tiers (repeat for each):"
echo "  Tier 0  (governance, 100% discount): terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":0,\"min_cl8y_balance\":\"0\",\"discount_bps\":10000,\"governance_only\":true}}' ..."
echo "  Tier 1  (1 CL8Y, 10% discount):     terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":1,\"min_cl8y_balance\":\"1000000000000000000\",\"discount_bps\":1000,\"governance_only\":false}}' ..."
echo "  Tier 2  (50 CL8Y, 25% discount):    terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":2,\"min_cl8y_balance\":\"50000000000000000000\",\"discount_bps\":2500,\"governance_only\":false}}' ..."
echo "  Tier 3  (200 CL8Y, 35% discount):   terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":3,\"min_cl8y_balance\":\"200000000000000000000\",\"discount_bps\":3500,\"governance_only\":false}}' ..."
echo "  Tier 4  (1000 CL8Y, 50% discount):  terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":4,\"min_cl8y_balance\":\"1000000000000000000000\",\"discount_bps\":5000,\"governance_only\":false}}' ..."
echo "  Tier 5  (15000 CL8Y, 80% discount): terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":5,\"min_cl8y_balance\":\"15000000000000000000000\",\"discount_bps\":8000,\"governance_only\":false}}' ..."
echo "  Tier 255 (blacklist, 0% discount):   terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_tier\":{\"tier_id\":255,\"min_cl8y_balance\":\"0\",\"discount_bps\":0,\"governance_only\":true}}' ..."
echo ""
echo "Add trusted router:"
echo "  terrad tx wasm execute <FEE_DISCOUNT_ADDRESS> '{\"add_trusted_router\":{\"router\":\"<ROUTER_ADDRESS>\"}}' ..."
echo ""
echo "Set discount registry on all pairs:"
echo "  terrad tx wasm execute <FACTORY_ADDRESS> '{\"set_discount_registry_all\":{\"registry\":\"<FEE_DISCOUNT_ADDRESS>\"}}' ..."
echo ""

echo "Step 7: Verify deployment"
echo "========================="
echo ""
echo "Query factory config:"
echo "  terrad query wasm contract-state smart <FACTORY_ADDRESS> '{\"config\": {}}' --node $NODE --output json"
echo ""
echo "Query router config:"
echo "  terrad query wasm contract-state smart <ROUTER_ADDRESS> '{\"config\": {}}' --node $NODE --output json"
echo ""
echo "Query fee discount config:"
echo "  terrad query wasm contract-state smart <FEE_DISCOUNT_ADDRESS> '{\"config\": {}}' --node $NODE --output json"
echo ""
echo "Query fee discount tiers:"
echo "  terrad query wasm contract-state smart <FEE_DISCOUNT_ADDRESS> '{\"get_tiers\": {}}' --node $NODE --output json"
echo ""
echo "=============================================="
echo "Update frontend-dapp/.env with:"
echo "  VITE_FACTORY_ADDRESS=<FACTORY_ADDRESS>"
echo "  VITE_ROUTER_ADDRESS=<ROUTER_ADDRESS>"
echo "  VITE_FEE_DISCOUNT_ADDRESS=<FEE_DISCOUNT_ADDRESS>"
echo "  VITE_CL8Y_TOKEN_ADDRESS=terra16wtml2q66g82fdkx66tap0qjkahqwp4lwq3ngtygacg5q0kzycgqvhpax3"
echo "  VITE_NETWORK=$NETWORK"
echo "=============================================="
